version: "3.8"
services:
  grafana:
    image: grafana/grafana:8.4.6
    networks:
      - traefik_public
      - internal
    volumes:
      - var_lib_grafana:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Default
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_OAUTH_AUTO_LOGIN=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_USERS_ALLOW_SIGN_UP=false
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.grafana.rule: "Host(`grafana.${DOMAIN:?}`)"
        traefik.http.routers.grafana.entrypoints: "websecure"
        traefik.http.routers.grafana.tls.certresolver: "letsencrypt"
        traefik.http.routers.grafana.service: "grafana"
        traefik.http.services.grafana.loadbalancer.server.port: 3000
        traefik.http.routers.grafana.middlewares: grafana-auth
        traefik.http.middlewares.grafana-auth.forwardauth.address: http://cloudflare-auth:8080/auth/${CLOUDFLARE_AUTH_AUD:?}

networks:
  traefik_public:
    external: true
  internal:
    external: true
  

volumes:
  var_lib_grafana:
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER:?},nfsvers=4
      device: :/grafana_var_lib_grafana
